### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by jerrylin3321** [thisisandreeeee/stalk-the-DMV#5]
The DMV has put in reCaptcha sometime since this program was written. Are there any ways to bypass this captcha?

**Comment by jkdao** [comment]
There's no way to bypass recaptcha with a bot (yet) so time would probably have to be alotted via a delay for you to complete it manually.

**Comment by jerrylin3321** [comment]
I had some success using this extension called Buster to bypass the captcha. It's not perfect — Google can somehow detect that the captcha is being automated — but if you keep on trying to bust the captcha, I've found that it'll let you eventually.
